// Generated by bench2verilog.py
module decoder_2x4(
    A, B, Y0, Y1, Y2, Y3
);

  input  A, B;
  output Y0, Y1, Y2, Y3;
  wire   CONST0, CONST1, n_not_A, n_not_B, p_Y0_0, p_Y1_0, p_Y2_0, p_Y3_0;

  assign CONST0 = (A & n_not_A);
  assign CONST1 = (A | n_not_A);
  assign Y0 = p_Y0_0;
  assign Y1 = p_Y1_0;
  assign Y2 = p_Y2_0;
  assign Y3 = p_Y3_0;
  assign n_not_A = ~(A);
  assign n_not_B = ~(B);
  assign p_Y0_0 = (n_not_A & n_not_B);
  assign p_Y1_0 = (n_not_A & B);
  assign p_Y2_0 = (A & n_not_B);
  assign p_Y3_0 = (A & B);

endmodule
